export interface registerEmpInfoType {          
    empName: string, 
    gender: string | null,  
    birthDate: string,
    socialSecurityNo: string,
    phoneNumber: string,      
    address: string,   
    addressDetail: string,
    educationLevel: string,
    postalCode: string,
    email: string,
    hireDate: string,
    deptCode: string | null,
    positionCode: string | null,
    workContract: string | null,
    workExperience: string | null,
    authCode: string | null,
    createdBy: string,
}